---
- hosts: ucd_server
#  gather_facts: yes
  become: yes
  tasks:

  - name: include urbancode variables
    include_vars:
      dir: ../deploy-urbancode-deploy/group_vars
  - name: Include JPetStore related vars
    include_vars:
      dir: vars

  - name: create a download directory if not exists
    file:
      path: "{{ download_dir }}/{{ demo.name }}"
      state: directory
      recurse: yes

# Component artifacts: /home/JPetStore/shared/.... -> available from zip file
  - name: download JPetStore-Artifacts pack
    copy:
      src: "{{ demo.source_directory }}/{{ demo.name }}/{{ demo.artifact_binaries }}"
      dest: "{{ download_dir }}/{{ demo.name }}"

  - name: unzip JPetStore-Artifacts pack
    unarchive:
      src: "{{ download_dir }}/{{ demo.name }}/{{ demo.artifact_binaries }}"
      dest: "{{ demo.target_directory }}"
      creates: "{{ demo.target_directory }}/{{ demo.name }}"
      remote_src: yes

  - name: set owner of JPetStore artifacts directory to running user
    file:
      path: "{{ demo.target_directory }}/{{ demo.name }}"
      state: directory
      recurse: yes
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"

  - name: create webserver directory if not exists
    file:
      path: "{{ a_t.target_directory }}"
      state: directory
      recurse: yes

# download  apache tomcat for the environments sit and uat 
  - name: download apache tomcat
    get_url: 
      url: "{{ a_t_download_url }}"
      dest: "{{ download_dir }}"

# unzip archive and copy it to destination directories 
  - name: unzip apache tomcat archive
    unarchive:
      src: "{{ download_dir }}/{{ a_t.file_name }}.{{ a_t.file_extension }}"
      dest: "{{ download_dir }}"
      creates: "{{ download_dir }}/{{ a_t.file_name }}"
      remote_src: yes

  - name: copy to target directory
    copy: 
      src: "{{ download_dir }}/{{ a_t.file_name }}/"
      dest: "{{ a_t.target_directory }}/{{ item.key}}-{{ a_t.file_name }}"
      remote_src: yes
    loop: "{{ lookup('dict', demo.environments) }}"

  - name: change non ssl ports in server.xml
    replace:
      path: "{{ a_t.target_directory }}/{{ item.key }}-{{ a_t.file_name }}/conf/server.xml"
      regexp: "{{a_t.standard_ports.non_ssl_port }}" 
      replace: "{{ item.value.non_ssl_port }}" 
    loop: "{{ lookup('dict', demo.environments) }}"

  - name: change ssl ports in server.xml
    replace:
      path: "{{ a_t.target_directory }}/{{ item.key }}-{{ a_t.file_name }}/conf/server.xml"
      regexp: "{{a_t.standard_ports.ssl_port }}" 
      replace: "{{ item.value.ssl_port }}" 
    loop: "{{ lookup('dict', demo.environments) }}"


  - name: copy tomcatusers
    copy:
      src: "{{ demo.source_directory }}/{{ demo.name }}/{{ a_t.tomcat_users_file }}"
      dest: "{{ a_t.target_directory }}/{{ item.key}}-{{ a_t.file_name }}/conf"
    loop: "{{ lookup('dict', demo.environments) }}"

# create resource tree
#TODO: check first if exists... then create
  - name: create top level resource
    uri:
        url: "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/cli/resource/create"
        user: "{{ ucds_admin_user }}"
        password: "{{ ucds_initial_admin_pwd }}"
        method: PUT
        body: ' { "name" : "{{ demo.name }}-Demo-Lab" }'
        force_basic_auth: yes
        body_format: json
        validate_certs: no
#        status_code: 204
  - name: create environment level resource
    uri:
        url: "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/cli/resource/create"
        user: "{{ ucds_admin_user }}"
        password: "{{ ucds_initial_admin_pwd }}"
        method: PUT
        body: ' { "name" : "{{ item.key | upper}}" ,"parent" : "\/{{ demo.name }}-Demo-Lab" }'
        force_basic_auth: yes
        body_format: json
        validate_certs: no
    loop: "{{ lookup('dict', demo.environments) }}"

  - name: add agent to environment
    uri:
        url: "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/cli/resource/create"
        user: "{{ ucds_admin_user }}"
        password: "{{ ucds_initial_admin_pwd }}"
        method: PUT
        body: ' { "agent" : "{{ ucd_agent_name }}" ,"parent" : "\/{{ demo.name }}-Demo-Lab\/{{ item.key | upper}}" }'
        force_basic_auth: yes
        body_format: json
        validate_certs: no
    loop: "{{ lookup('dict', demo.environments) }}"

#TODO: check if app exists if yes use update artifact setting if no just import with create
# import application 
  - name: import JPetStore demo application
    shell: 'curl -v -k -u  "{{ ucds_admin_user }}:{{ ucds_initial_admin_pwd }}" -X POST -H "Content-Type: multipart/form-data" -F "file=@{{ demo.name }}.json" "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/rest/deploy/application/import?upgradeType=USE_EXISTING_IF_EXISTS&compTempUpgradeType=USE_EXISTING_IF_EXISTS&processUpgradeType=USE_EXISTING_IF_EXISTS&resourceTemplateUpgradeType=USE_EXISTING_IF_EXISTS&appTempUpgradeType=USE_EXISTING_IF_EXISTS"'
    args:  
      chdir: "{{ demo.target_directory }}/{{ demo.name }}"

# import component versions 
  - name: import JPetStore component versions
    uri:
        url: "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/cli/component/integrate"
        user: "{{ ucds_admin_user }}"
        password: "{{ ucds_initial_admin_pwd }}"
        method: PUT
        body: ' { "component" : "{{ item }}" }'
        force_basic_auth: yes
        body_format: json
        validate_certs: no
    loop: "{{ demo.components }}"

  
  - name: add components to agents
    uri:
        url: "https://{{ ucd_server_hostname }}:{{ install_server_web_https_port }}/cli/resource/create"
        user: "{{ ucds_admin_user }}"
        password: "{{ ucds_initial_admin_pwd }}"
        method: PUT
        body: ' { "component" : "{{ item[1] }}" ,"parent" : "\/{{ demo.name }}-Demo-Lab\/{{ item.0.key | upper}}\/{{ ucd_agent_name }}" }'
        force_basic_auth: yes
        body_format: json
        validate_certs: no
    with_nested: 
      - "{{ lookup('dict', demo.environments) }}"
      - "{{ demo.components }}"

  - name: set JPetStore Firewalld settings
    firewalld:
      port: "{{ item.value.non_ssl_port }}/tcp"
      permanent: yes
      immediate: yes
      state: enabled
    loop: "{{ lookup('dict', demo.environments) }}"
    when: ansible_facts['os_family'] == "RedHat" 

  - name: set JPetStore UFW settings
    firewalld:
      port: "{{ item.value.non_ssl_port }}"
      proto: tcp
      rule: allow
      state: enabled
    loop: "{{ lookup('dict', demo.environments) }}"
    when: ansible_facts['os_family'] == "Ubuntu" 

# create databases for JPetStore Environments 
- hosts: db_server
  become: yes
  gather_facts: yes
  pre_tasks:

  - name: Include JPetStore related vars
    include_vars:
      file: vars/jpetstore_demo_variables.yml

  roles: 
    - role: robertdebock.mysql

  post_tasks:
    - name: create jpetstore databaes
      mysql_db:
        name: "{{ demo.db.name }}_{{ item.key}}" 
        encoding: utf8
        collation: utf8_bin
        state: present
      loop: "{{ lookup('dict', demo.environments) }}"
    
    - name: create jpetstore user
      mysql_user:
        name: "{{ demo.db.user }}"
        password: "{{ demo.db.password }}"
        host: "localhost"

    - name: add grant to  jpetstore User
      mysql_user: 
        name: "{{ demo.db.user }}" 
        append_privs: yes
        priv: "{{ demo.db.name }}_{{ item.key}}.*:ALL,GRANT" 
        host: "%" 
        state: present
      loop:  "{{ lookup('dict', demo.environments) }}"

